name: stuverse_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  cached_network_image:
    git:
      url: https://github.com/prashantsolankispaceo/cached_network_image.git
      path: cached_network_image
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.8.1
  confetti: ^0.7.0
  dio: ^5.2.1+1
  filter_list: ^1.0.2
  firebase_core: ^2.14.0
  firebase_messaging: ^14.6.3
  flex_color_scheme: ^7.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_local_notifications: ^14.1.1
  flutter_svg: ^2.0.7
  font_awesome_flutter: ^10.4.0
  google_fonts: ^5.0.0
  google_nav_bar: ^5.0.6
  image_picker: ^0.8.9
  intl: ^0.18.1
  loading_animation_widget: ^1.2.0+4
  lottie: ^2.4.0
  razorpay_flutter: ^1.3.5
  shared_preferences: ^2.1.2
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
